export default {
  GET_USERS_START: 'GET_USERS_START',
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
  GET_USERS_FAIL: 'GET_USERS_FAIL',

  FILTER_USERS_BY_CATEGORY: 'FILTER_USERS_BY_CATEGORY',
  FILTER_USERS_BY_SEARCH: 'FILTER_USERS_BY_SEARCH',
  TURN_OFF_USERS_FILTER: 'TURN_OFF_USERS_FILTER',
};
