export default {
  GET_ADMINS_START: 'GET_ADMINS_START',
  GET_ADMINS_SUCCESS: 'GET_ADMINS_SUCCESS',
  GET_ADMINS_FAIL: 'GET_ADMINS_FAIL',

  ON_CHANGE_NEW_ADMIN_TEXT_FIELD: 'ON_CHANGE_NEW_ADMIN_TEXT_FIELD',
};
