export default {
  GET_COMPANIES_START: 'GET_COMPANIES_START',
  GET_COMPANIES_SUCCESS: 'GET_COMPANIES_SUCCESS',
  GET_COMPANIES_FAIL: 'GET_COMPANIES_FAIL',

  FILTER_COMPANIES_BY_COUNTRY: 'FILTER_COMPANIES_BY_COUNTRY',
  FILTER_COMPANIES_BY_SEARCH: 'FILTER_COMPANIES_BY_SEARCH',
  TURN_OFF_COMPANIES_FILTER: 'TURN_OFF_COMPANIES_FILTER',

  DELETE_COMPANY_START: 'DELETE_COMPANY_START',
  DELETE_COMPANY_SUCCESS: 'DELETE_COMPANY_SUCCESS',
  DELETE_COMPANY_FAIL: 'DELETE_COMPANY_FAIL',
};
