export default {
  ON_CHANGE_USERS_TABLE_SETTINGS: 'ON_CHANGE_USERS_TABLE_SETTINGS',
  ON_CHANGE_COMPANIES_TABLE_SETTINGS: 'ON_CHANGE_COMPANIES_TABLE_SETTINGS',
  ON_CHANGE_OFFERS_TABLE_SETTINGS: 'ON_CHANGE_OFFERS_TABLE_SETTINGS',
};
