export default {
  GET_REPORTS_START: 'GET_REPORTS_START',
  GET_REPORTS_SUCCESS: 'GET_REPORTS_SUCCESS',
  GET_REPORTS_FAIL: 'GET_REPORTS_FAIL',

  ON_FILTER_BY_REASON: 'ON_FILTER_BY_REASON',
  ON_FILTER_BY_SEARCH: 'ON_FILTER_BY_SEARCH',
  TURN_OFF_REPORTS_FILTER: 'TURN_OFF_REPORTS_FILTER',
};
