export default {
  GET_SESSIONS_START: 'GET_SESSIONS_START',
  GET_SESSIONS_SUCCESS: 'GET_SESSIONS_SUCCESS',
  GET_SESSIONS_FAIL: 'GET_SESSIONS_FAIL',

  ON_CHANGE_USER_SESSIONS_TIME: 'ON_CHANGE_USER_SESSIONS_TIME',
};
