export default {
  GET_SESSIONS_START: 'GET_SESSIONS_START',
  GET_SESSIONS_SUCCESS: 'GET_SESSIONS_SUCCESS',
  GET_SESSIONS_FAIL: 'GET_SESSIONS_FAIL',

  GET_SESSIONS_BY_DEVICE_START: 'GET_SESSIONS_BY_DEVICE_START',
  GET_SESSIONS_BY_DEVICE_SUCCESS: 'GET_SESSIONS_BY_DEVICE_SUCCESS',
  GET_SESSIONS_BY_DEVICE_FAIL: 'GET_SESSIONS_BY_DEVICE_FAIL',

  GET_USER_STATS_START: 'GET_USER_STATS_START',
  GET_USER_STATS_SUCCESS: 'GET_USER_STATS_SUCCESS',
  GET_USER_STATS_FAIL: 'GET_USER_STATS_FAIL',
  GET_USER_PREVIOUS_STATS_SUCCESS: 'GET_USER_PREVIOUS_STATS_SUCCESS',
  GET_USER_PREVIOUS_STATS_FAIL: 'GET_USER_PREVIOUS_STATS_FAIL',

  GET_USERS_GRAPH_START: 'GET_USERS_GRAPH_START',
  GET_USERS_GRAPH_SUCCESS: 'GET_USERS_GRAPH_SUCCESS',
  GET_USERS_GRAPH_FAIL: 'GET_USERS_GRAPH_FAIL',

  ON_CHANGE_REQUESTED_TIME: 'ON_CHANGE_REQUESTED_TIME',
};
