export default {
  GET_SESSIONS_START: 'GET_SESSIONS_START',
  GET_SESSIONS_SUCCESS: 'GET_SESSIONS_SUCCESS',
  GET_SESSIONS_FAIL: 'GET_SESSIONS_FAIL',

  GET_SESSIONS_BY_DEVICE_START: 'GET_SESSIONS_BY_DEVICE_START',
  GET_SESSIONS_BY_DEVICE_SUCCESS: 'GET_SESSIONS_BY_DEVICE_SUCCESS',
  GET_SESSIONS_BY_DEVICE_FAIL: 'GET_SESSIONS_BY_DEVICE_FAIL',

  ON_CHANGE_REQUESTED_TIME: 'ON_CHANGE_REQUESTED_TIME',
};
