export default {
  SEND_NOTIFICATION_START: 'SEND_NOTIFICATION_START',
  SEND_NOTIFICATION_SUCCESS: 'SEND_NOTIFICATION_SUCCESS',
  SEND_NOTIFICATION_FAIL: 'SEND_NOTIFICATION_FAIL',

  SET_INITIAL_COUNTRIES: 'SET_INITIAL_COUNTRIES',
  SET_INITIAL_CATEGORIES: 'SET_INITIAL_CATEGORIES',

  ON_CHANGE_NOTIFICATION_TEXT: 'ON_CHANGE_NOTIFICATION_TEXT',
  ON_CHANGE_NOTIFICATION_COUNTRY: 'ON_CHANGE_NOTIFICATION_COUNTRY',
  ON_CHANGE_NOTIFICATION_CATEGORY: 'ON_CHANGE_NOTIFICATION_CATEGORY',
  ON_CHANGE_NOTIFICATION_DATE: 'ON_CHANGE_NOTIFICATION_DATE',
  ON_CHANGE_NOTIFICATION_TIME: 'ON_CHANGE_NOTIFICATION_TIME',
};
