export default {
  GET_OFFERS_START: 'GET_OFFERS_START',
  GET_OFFERS_SUCCESS: 'GET_OFFERS_SUCCESS',
  GET_OFFERS_FAIL: 'GET_OFFERS_FAIL',

  FILTER_OFFERS_BY_CATEGORY: 'FILTER_OFFERS_BY_CATEGORY',
  FILTER_OFFERS_BY_PRICE: 'FILTER_OFFERS_BY_PRICE',
  FILTER_OFFERS_BY_SEARCH: 'FILTER_OFFERS_BY_SEARCH',
  TURN_OFF_OFFERS_FILTER: 'TURN_OFF_OFFERS_FILTER',
};
